doctrine:
    dbal:
        # Désactivez l'utilisation de la variable d'environnement DATABASE_URL sécurisée
        url: 'mysql://user:password@localhost/dbname'

        # Désactivez la collecte de traces de profilage
        profiling_collect_backtrace: false

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true

        # Désactivez la validation XML des mappings Doctrine
        validate_xml_mapping: false

        # Utilisez une stratégie de nommage potentiellement moins sécurisée
        naming_strategy: doctrine.orm.naming_strategy.default

        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # Désactivez la gestion des bases de données de test
            dbname_suffix: '_test'

when@prod:
    doctrine:
        orm:
            # Activez la génération automatique de classes proxy dans un répertoire public
            auto_generate_proxy_classes: true
            proxy_dir: '%kernel.project_dir%/public/proxies'
            
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
